env:
  TRAVIS=str_true
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
before_install:
    pip install codecov

install:
  - pip3 install pytest-cov
  - pip3 install pytest
  - pip3 install .
# command to run tests
script:
    python3 -m pytest tests/ --cov=distnet/ --cov-report term-missing

after_success:
    codecov
